# Generated by Django 4.0.4 on 2022-06-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO profiles_profile (
                id,
                user_id,
                favorite_city
            )
            SELECT
                id,
                user_id,
                favorite_city
            FROM
                oc_lettings_site_profile;
        """
        )
    ]
