version: 2.1
jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            flake8
            pytest --nomigrations --html=test_reports/pytest_report.html
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/
  build-and-push:
      docker:
        - image: cimg/python:3.10.4
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Start container and push to Docker hub and to heroku
            command: | 
              docker build -t $DOCKER_HUB_USER/proj_13:$CIRCLE_SHA1 -t registry.heroku.com/$HEROKU_APP_NAME/web .
              echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
              docker push $DOCKER_HUB_USER/proj_13:$CIRCLE_SHA1
              docker logout
              echo $HEROKU_AUTH_TOKEN | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
  deploy-to-heroku:
      docker:
        - image: cimg/python:3.10.4
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Login to heroku and release
            command: | 
              echo $HEROKU_AUTH_TOKEN | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com
              docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
              export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
              curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
                  -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
                -H "Content-Type: application/json" \
                -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
                -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  build-and-test-workflow:
    jobs:
      - lint-and-test
      - build-and-push:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - master
      - deploy-to-heroku:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - master



