version: 2.1
jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python -m venv venv
            venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            venv/bin/activate
            flake8
            pytest --nomigrations --html=test_reports/pytest_report.html
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/
  build-and-push-to-dockerhub:
      docker:
        - image: cimg/python:3.10.4
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Start container and push to Docker
            command: | 
              docker build -t $DOCKER_HUB_USER/proj_13:$CIRCLE_SHA1 .
              echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
              docker push $DOCKER_HUB_USER/proj_13:$CIRCLE_SHA1

workflows:
  build-and-test-workflow:
    jobs:
      - lint-and-test
      - build-and-push-to-dockerhub:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - master



